# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution-seatbelt: './Seatbelt/*.sln'
  solution-rubeus: './Rubeus/*.sln'
  solution-sharphound: './SharpHound3/*.sln'
  solution-sharpdump: './SharpDump/*.sln'
  solution-sharpshares: './SharpShares/*.sln'
  solution-bettersafetykatz: './BetterSafetyKatz/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution-seatbelt)'

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution-rubeus)'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution-sharphound)'

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution-sharpdump)'

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution-sharpshares)'

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution-bettersafetykatz)'

# build Seatbelt
- task: VSBuild@1
  inputs:
    solution: '$(solution-seatbelt)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    vsVersion: '16.0'
    msbuildArgs: '/p:TargetFrameworkVersion=v3.5'
    clean: true

# build Rubeus
- task: VSBuild@1
  inputs:
    solution: '$(solution-rubeus)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    vsVersion: '16.0'
    msbuildArgs: '/p:TargetFrameworkVersion=v3.5'
    clean: true

# build SharpHound3
# SharpHound3 doesn't like 3.5 either, so just build as usual
- task: VSBuild@1
  inputs:
    solution: '$(solution-sharphound)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    vsVersion: '16.0'
    clean: true

# build SharpDump
- task: VSBuild@1
  inputs:
    solution: '$(solution-sharpdump)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    vsVersion: '16.0'
    msbuildArgs: '/p:TargetFrameworkVersion=v3.5'
    clean: true

# build SharpShares
# SharpShares doesn't compile with 3.5, needs 4.0 at the very least
- task: VSBuild@1
  inputs:
    solution: '$(solution-sharpshares)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    vsVersion: '16.0'
    msbuildArgs: '/p:TargetFrameworkVersion=v4.0'
    clean: true

# build BetterSafetyKatz
- task: VSBuild@1
  inputs:
    solution: '$(solution-bettersafetykatz)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    vsVersion: '16.0'
    msbuildArgs: '/p:TargetFrameworkVersion=v3.5'
    clean: true

# copy Seatbelt to staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\Seatbelt\Seatbelt\bin\Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# copy Rubeus to staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\Rubeus\Rubeus\bin\Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# copy SharpHound3 to staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\SharpHound3\SharpHound3\bin\Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# copy SharpDump to staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\SharpDump\SharpDump\bin\Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# copy SharpDump to staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\SharpShares\bin\Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# copy SharpDump to staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\BetterSafetyKatz\BetterSafetyKatz\bin\Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# publish all the artifacts in one place
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
