# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution-seatbelt: './Seatbelt/*.sln'
  solution-rubeus: './Rubeus/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution-seatbelt)'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution-rubeus)'

- task: VSBuild@1
  inputs:
    solution: '$(solution-seatbelt)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    vsVersion: '16.0'
    msbuildArgs: '/p:AssemblyName=DefoNotSeatbelt'
    clean: true

- task: VSBuild@1
  inputs:
    solution: '$(solution-rubeus)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    vsVersion: '16.0'
    msbuildArgs: '/p:AssemblyName=DefoNotRubeus'
    clean: true

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\Seatbelt\Seatbelt\bin\Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\Rubeus\Rubeus\bin\Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'