# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution-seatbelt: './Seatbelt/*.sln'
  solution-rubeus: './Rubeus/*.sln'
  solution-sharphound: './SharpHound3/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution-seatbelt)'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution-rubeus)'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution-sharphound)'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'

# build Seatbelt
- task: VSBuild@1
  inputs:
    solution: '$(solution-seatbelt)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    vsVersion: '16.0'
    msbuildArgs: '/p:AssemblyName=DefoNotSeatbelt /p:TargetFrameworkVersion=v3.0'
    clean: true

# build Rubeus
- task: VSBuild@1
  inputs:
    solution: '$(solution-rubeus)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    vsVersion: '16.0'
    msbuildArgs: '/p:AssemblyName=DefoNotRubeus'
    clean: true

# build SharpHound3
- task: VSBuild@1
  inputs:
    solution: '$(solution-sharphound)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    vsVersion: '16.0'
    msbuildArgs: '/p:AssemblyName=DefoNotSharpHound3'
    clean: true

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

# copy Seatbelt to staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\Seatbelt\Seatbelt\bin\Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# copy Rubeus to staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\Rubeus\Rubeus\bin\Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# copy SharpHound3 to staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\SharpHound3\SharpHound3\bin\Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# publish all the artifacts in one place
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
